networks:
  php-otel:

services:
  order-service:
    build:
      context: ./
      dockerfile: dockerfiles/order.dockerfile
    command: >
      sh -c "php artisan serve --host=0.0.0.0 --port=8000"
    container_name: order-service
    volumes:
      - ./order-service:/var/www/html
    ports:
      - "8000:8000"
    networks:
      - php-otel
  shipping-service:
    build:
      context: ./
      dockerfile: dockerfiles/shipping.dockerfile
    command: >
      sh -c "php artisan serve --host=0.0.0.0 --port=8000"
    container_name: shipping-service
    volumes:
      - ./shipping-service:/var/www/html
    ports:
      - "8001:8000"
    networks:
      - php-otel
  queue-worker:
    build:
      context: ./
      dockerfile: dockerfiles/order.dockerfile
    command: >
      sh -c "php artisan queue:work"
    container_name: order-queue
    volumes:
      - ./order-service:/var/www/html
    networks:
      - php-otel
  postgres:
    image: postgres:15.10-alpine
    volumes:
      - "postgres_data:/var/lib/postgresql/data"
    container_name: phpArchDb
    environment:
      - POSTGRES_USER=nelwhix
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=phparch-db
    ports:
      - "5432:5432"
    networks:
      - php-otel
  zipkin:
    image: openzipkin/zipkin-slim
    ports:
      - "9411:9411"
    networks:
      - php-otel
volumes:
  postgres_data:
    driver: local